# Generated by Django 4.0.2 on 2022-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='marketplace/media/default.jpg', upload_to='marketplace/media/%Y/%m/%d'),
        ),
    ]
